- name: restrict-irc-relay
  match: irc-relay
  allow:
    - pod: bot
    - pod: grafana-alloy

- name: restrict-core
  match: core
  allow:
    - pod: bot

- name: restrict-redis
  match: redis
  allow:
    - pod: bot
    - pod: report-interface

- name: restrict-grafana-alloy
  match: grafana-alloy
  allow:
    - namespace: tool-cluebotng-monitoring

- name: restrict-pushgateway
  match: pushgateway
  allow:
    - namespace: tool-cluebotng

# Cleanup
- name: limit-access-irc-relay
  delete: True

- name: limit-access-core
  delete: True
