name: 'Trigger deploy for cluebotng-trainer'
on: { push: { branches: [ main ], paths: [ 'cluebotng-trainer.yaml', '.github/workflows/cluebotng-trainer.yaml' ] } }
jobs:
  update-config:
    runs-on: ubuntu-latest
    concurrency:
      group: cluebotng-trainer-update-config
    steps:
      - uses: actions/checkout@v4
      - uses: cluebotng/ci-execute-fabric@main
        with:
          user: 'cluebotng-trainer'
          task: setup
          ssh_key: ${{ secrets.CI_SSH_KEY }}
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: cluebotng-trainer-deploy
    #environment: 'cluebotng-trainer'
    needs: [update-config]
    steps:
      - uses: actions/checkout@v4
      - uses: cluebotng/ci-execute-fabric@main
        with:
          user: 'cluebotng-trainer'
          task: execute-deploy
          ssh_key: ${{ secrets.CI_SSH_KEY }}
      # - uses: cluebotng/ci-toolforge-deploy@main
      #   with:
      #      tool: 'cluebotng-trainer'
      #     token: '${{ secrets.TOOLFORGE_DEPLOY_TOKEN }}'
